// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_STDOUT                 LogStream = 1
	LogStream_STDERR                 LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"STDOUT":                 1,
		"STDERR":                 2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

// ----------------------------
// LIST CONTAINERS
// ----------------------------
type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

// ----------------------------
// LIST IMAGES
// ----------------------------
type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      string                 `protobuf:"bytes,2,opt,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetRepoTags() string {
	if x != nil {
		return x.RepoTags
	}
	return ""
}

func (x *Image) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Image) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

// ------------------------------
// STOP, START EXISTING CONTAINER BY ID
// -----------------------------
type ContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRequest) Reset() {
	*x = ContainerRequest{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequest) ProtoMessage() {}

func (x *ContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequest.ProtoReflect.Descriptor instead.
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerResponse) Reset() {
	*x = ContainerResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerResponse) ProtoMessage() {}

func (x *ContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerResponse.ProtoReflect.Descriptor instead.
func (*ContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

// -------------------------------
// REMOVE CONTAINER
// ------------------------------
type RemoveContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	RemoveVolumes bool                   `protobuf:"varint,3,opt,name=remove_volumes,json=removeVolumes,proto3" json:"remove_volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveContainerRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RemoveContainerRequest) GetRemoveVolumes() bool {
	if x != nil {
		return x.RemoveVolumes
	}
	return false
}

// --------------------------------
// RUN CONTAINER
// ---------------------------------
type RunContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"` // ["KEY=value"]
	Ports         []*PortBinding         `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes       []*VolumeBinding       `protobuf:"bytes,6,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Tty           bool                   `protobuf:"varint,7,opt,name=tty,proto3" json:"tty,omitempty"`
	Detach        bool                   `protobuf:"varint,8,opt,name=detach,proto3" json:"detach,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerRequest) Reset() {
	*x = RunContainerRequest{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerRequest) ProtoMessage() {}

func (x *RunContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerRequest.ProtoReflect.Descriptor instead.
func (*RunContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RunContainerRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RunContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunContainerRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunContainerRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunContainerRequest) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *RunContainerRequest) GetVolumes() []*VolumeBinding {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *RunContainerRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *RunContainerRequest) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort string                 `protobuf:"bytes,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"` // "80/tcp"
	HostPort      string                 `protobuf:"bytes,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`                // "8080"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PortBinding) GetContainerPort() string {
	if x != nil {
		return x.ContainerPort
	}
	return ""
}

func (x *PortBinding) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

type VolumeBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeBinding) Reset() {
	*x = VolumeBinding{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBinding) ProtoMessage() {}

func (x *VolumeBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBinding.ProtoReflect.Descriptor instead.
func (*VolumeBinding) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *VolumeBinding) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeBinding) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// ------------------------------------
// VIEW LOGS
// --------------------------------------
type ViewLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // like docker logs -f
	Tail          uint32                 `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`     // last N lines (0 = all)
	Timestamps    bool                   `protobuf:"varint,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewLogsRequest) Reset() {
	*x = ViewLogsRequest{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewLogsRequest) ProtoMessage() {}

func (x *ViewLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewLogsRequest.ProtoReflect.Descriptor instead.
func (*ViewLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ViewLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ViewLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *ViewLogsRequest) GetTail() uint32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *ViewLogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=agent.LogStream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogMessage) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogMessage) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\x17\n" +
	"\x15ListContainersRequest\"]\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"J\n" +
	"\x16ListContainersResponse\x120\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x10.agent.ContainerR\n" +
	"containers\"\x13\n" +
	"\x11ListImagesRequest\"b\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x01(\tR\brepoTags\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\":\n" +
	"\x12ListImagesResponse\x12$\n" +
	"\x06images\x18\x01 \x03(\v2\f.agent.ImageR\x06images\"\"\n" +
	"\x10ContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11ContainerResponse\"e\n" +
	"\x16RemoveContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12%\n" +
	"\x0eremove_volumes\x18\x03 \x01(\bR\rremoveVolumes\"\xf4\x01\n" +
	"\x13RunContainerRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12(\n" +
	"\x05ports\x18\x05 \x03(\v2\x12.agent.PortBindingR\x05ports\x12.\n" +
	"\avolumes\x18\x06 \x03(\v2\x14.agent.VolumeBindingR\avolumes\x12\x10\n" +
	"\x03tty\x18\a \x01(\bR\x03tty\x12\x16\n" +
	"\x06detach\x18\b \x01(\bR\x06detach\"Q\n" +
	"\vPortBinding\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\tR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\tR\bhostPort\"?\n" +
	"\rVolumeBinding\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x80\x01\n" +
	"\x0fViewLogsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\rR\x04tail\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x04 \x01(\bR\n" +
	"timestamps\"J\n" +
	"\n" +
	"LogMessage\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12(\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x10.agent.LogStreamR\x06stream*?\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x022\xf4\x03\n" +
	"\fAgentService\x12A\n" +
	"\n" +
	"ListImages\x12\x18.agent.ListImagesRequest\x1a\x19.agent.ListImagesResponse\x12M\n" +
	"\x0eListContainers\x12\x1c.agent.ListContainersRequest\x1a\x1d.agent.ListContainersResponse\x12B\n" +
	"\rStopContainer\x12\x17.agent.ContainerRequest\x1a\x18.agent.ContainerResponse\x12C\n" +
	"\x0eStartContainer\x12\x17.agent.ContainerRequest\x1a\x18.agent.ContainerResponse\x12J\n" +
	"\x0fRemoveContainer\x12\x1d.agent.RemoveContainerRequest\x1a\x18.agent.ContainerResponse\x12D\n" +
	"\fRunContainer\x12\x1a.agent.RunContainerRequest\x1a\x18.agent.ContainerResponse\x127\n" +
	"\bViewLogs\x12\x16.agent.ViewLogsRequest\x1a\x11.agent.LogMessage0\x01B\x0eZ\f/agent/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_proto_goTypes = []any{
	(LogStream)(0),                 // 0: agent.LogStream
	(*ListContainersRequest)(nil),  // 1: agent.ListContainersRequest
	(*Container)(nil),              // 2: agent.Container
	(*ListContainersResponse)(nil), // 3: agent.ListContainersResponse
	(*ListImagesRequest)(nil),      // 4: agent.ListImagesRequest
	(*Image)(nil),                  // 5: agent.Image
	(*ListImagesResponse)(nil),     // 6: agent.ListImagesResponse
	(*ContainerRequest)(nil),       // 7: agent.ContainerRequest
	(*ContainerResponse)(nil),      // 8: agent.ContainerResponse
	(*RemoveContainerRequest)(nil), // 9: agent.RemoveContainerRequest
	(*RunContainerRequest)(nil),    // 10: agent.RunContainerRequest
	(*PortBinding)(nil),            // 11: agent.PortBinding
	(*VolumeBinding)(nil),          // 12: agent.VolumeBinding
	(*ViewLogsRequest)(nil),        // 13: agent.ViewLogsRequest
	(*LogMessage)(nil),             // 14: agent.LogMessage
}
var file_proto_agent_proto_depIdxs = []int32{
	2,  // 0: agent.ListContainersResponse.containers:type_name -> agent.Container
	5,  // 1: agent.ListImagesResponse.images:type_name -> agent.Image
	11, // 2: agent.RunContainerRequest.ports:type_name -> agent.PortBinding
	12, // 3: agent.RunContainerRequest.volumes:type_name -> agent.VolumeBinding
	0,  // 4: agent.LogMessage.stream:type_name -> agent.LogStream
	4,  // 5: agent.AgentService.ListImages:input_type -> agent.ListImagesRequest
	1,  // 6: agent.AgentService.ListContainers:input_type -> agent.ListContainersRequest
	7,  // 7: agent.AgentService.StopContainer:input_type -> agent.ContainerRequest
	7,  // 8: agent.AgentService.StartContainer:input_type -> agent.ContainerRequest
	9,  // 9: agent.AgentService.RemoveContainer:input_type -> agent.RemoveContainerRequest
	10, // 10: agent.AgentService.RunContainer:input_type -> agent.RunContainerRequest
	13, // 11: agent.AgentService.ViewLogs:input_type -> agent.ViewLogsRequest
	6,  // 12: agent.AgentService.ListImages:output_type -> agent.ListImagesResponse
	3,  // 13: agent.AgentService.ListContainers:output_type -> agent.ListContainersResponse
	8,  // 14: agent.AgentService.StopContainer:output_type -> agent.ContainerResponse
	8,  // 15: agent.AgentService.StartContainer:output_type -> agent.ContainerResponse
	8,  // 16: agent.AgentService.RemoveContainer:output_type -> agent.ContainerResponse
	8,  // 17: agent.AgentService.RunContainer:output_type -> agent.ContainerResponse
	14, // 18: agent.AgentService.ViewLogs:output_type -> agent.LogMessage
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
