syntax = "proto3";

package agent;

option go_package = "/agent/proto";

service AgentService {
  // images
  rpc ListImages(ListImagesRequest) returns (ListImagesResponse);
  rpc RemoveImage(RemoveImageRequest) returns (RemoveImageResponse);

  // containers
  rpc ListContainers(ListContainersRequest) returns (ListContainersResponse);
  rpc InspectContainer(ContainerRequest) returns (InspectContainerResponse);
  rpc ContainerStats(ContainerRequest) returns (stream ContainerStatsResponse);

  // containers movements 
  rpc StopContainer(ContainerRequest) returns (ContainerResponse);
  rpc StartContainer(ContainerRequest) returns (ContainerResponse);
  rpc RemoveContainer(RemoveContainerRequest) returns (ContainerResponse);
  rpc RunContainer(RunContainerRequest) returns (ContainerResponse);

  // logs
  rpc ViewLogs(ViewLogsRequest) returns (stream LogMessage);
}

// ----------------------------
// LIST CONTAINERS 
// ----------------------------
message ListContainersRequest {}

message Container {
  string id = 1;
  string name = 2;
  string image = 3;
  string status = 4;
}

message ListContainersResponse {
  repeated Container containers = 1;
}


// ----------------------------
// LIST IMAGES 
// ----------------------------
message ListImagesRequest {}

message Image {
  string id = 1;
  string repo_tags = 2;
  int64 size = 3;
  int64 created = 4;
}

message ListImagesResponse {
  repeated Image images = 1;
}


// -------------------------------
// REMOVE IMAGE 
// -------------------------------
message RemoveImageRequest {
    string id = 1;
    bool force = 2;
}
message RemoveImageResponse {}


// ------------------------------
// STOP, START EXISTING CONTAINER BY ID
// -----------------------------
message ContainerRequest { string id = 1; }
message ContainerResponse {}


// -------------------------------
// REMOVE CONTAINER
// ------------------------------
message RemoveContainerRequest {
    string id = 1;
    bool force = 2;
    bool remove_volumes = 3;
}

// --------------------------------
// RUN CONTAINER
// ---------------------------------
message RunContainerRequest {
  string image_id = 1;

  string name = 2;
  repeated string command = 3;
  repeated string env = 4;      // ["KEY=value"]
  repeated PortBinding ports = 5;
  repeated VolumeBinding volumes = 6;
  bool tty = 7;
  bool detach = 8;
}

message PortBinding {
  string container_port = 1;    // "80/tcp"
  string host_ip = 2;
  string host_port = 3;         // "8080"
}

message VolumeBinding {
  string source = 1;
  string target = 2;
}

// ------------------------------------
// VIEW LOGS
// --------------------------------------
message ViewLogsRequest {
  string container_id = 1;

  bool follow = 2;            // like docker logs -f
  uint32 tail = 3;            // last N lines (0 = all)
  bool timestamps = 4;
}

enum LogStream {
    LOG_STREAM_UNSPECIFIED = 0;
    STDOUT = 1;
    STDERR = 2;
}

message LogMessage {
    string line = 1;
    LogStream stream = 2;
}


// -------------------------------------
// INSPECT CONTAINER
// ------------------------------------
message InspectContainerResponse {
    string id = 1;
    string name = 2;
    string image = 3;
    string status = 4;

    repeated PortBinding ports = 5;
    repeated VolumeBinding mounts = 6;
    repeated string env = 7;

    HealthStatus health = 8;
}

message HealthStatus {
    string status = 1;
    int32 failing_streak = 2;
    repeated string logs = 3;
}

// ---------------------------------------
// CONTAINER STATS
// ---------------------------------------
message ContainerStatsResponse {
  double cpu_percent = 1;

  uint64 memory_usage = 2;
  uint64 memory_limit = 3;

  uint64 network_rx = 4;
  uint64 network_tx = 5;

  uint64 block_read = 6;
  uint64 block_write = 7;

  uint32 pids = 8;
}
