syntax = "proto3";

package agent;

option go_package = "/agent/proto";

service AgentService {
  // images
  rpc ListImages(ListImagesRequest) returns (ListImagesResponse);

  // containers
  rpc ListContainers(ListContainersRequest) returns (ListContainersResponse);
  rpc StopContainer(ContainerRequest) returns (ContainerResponse);
  rpc StartContainer(ContainerRequest) returns (ContainerResponse);
  rpc RemoveContainer(RemoveContainerRequest) returns (ContainerResponse);
  rpc RunContainer(RunContainerRequest) returns (ContainerResponse);

  // logs
  rpc ViewLogs(ViewLogsRequest) returns (stream LogMessage);
}

// ----------------------------
// LIST CONTAINERS 
// ----------------------------
message ListContainersRequest {}

message Container {
  string id = 1;
  string name = 2;
  string image = 3;
  string status = 4;
}

message ListContainersResponse {
  repeated Container containers = 1;
}


// ----------------------------
// LIST IMAGES 
// ----------------------------
message ListImagesRequest {}

message Image {
  string id = 1;
  string repo_tags = 2;
  int64 size = 3;
  int64 created = 4;
}

message ListImagesResponse {
  repeated Image images = 1;
}


// ------------------------------
// STOP, START EXISTING CONTAINER BY ID
// -----------------------------
message ContainerRequest { string id = 1; }
message ContainerResponse {}


// -------------------------------
// REMOVE CONTAINER
// ------------------------------
message RemoveContainerRequest {
    string id = 1;
    bool force = 2;
    bool remove_volumes = 3;
}

// --------------------------------
// RUN CONTAINER
// ---------------------------------
message RunContainerRequest {
  string image_id = 1;

  string name = 2;
  repeated string command = 3;
  repeated string env = 4;      // ["KEY=value"]
  repeated PortBinding ports = 5;
  repeated VolumeBinding volumes = 6;
  bool tty = 7;
  bool detach = 8;
}

message PortBinding {
  string container_port = 1;    // "80/tcp"
  string host_port = 2;         // "8080"
}

message VolumeBinding {
  string source = 1;
  string target = 2;
}

// ------------------------------------
// VIEW LOGS
// --------------------------------------
message ViewLogsRequest {
  string container_id = 1;

  bool follow = 2;            // like docker logs -f
  uint32 tail = 3;            // last N lines (0 = all)
  bool timestamps = 4;
}

message LogMessage {
  string line = 1;
}
